### ISSUE TITLE
Control layer for transitions

### ISSUE THREAD

**Issue by beralt85** [sozi-projects/Sozi#287]
First: Sozi is the most awsome think ever. It totally fits my open workflow. I use Sozi mostly for scientific presentations. With the old Sozi13 inkscape extension, I had the following workflow:
1. I create an SVG file (Inkscape), that is mostly arranged in classical slides, but uses the sliding/zooming when a didactic effect can be sustained
2. I create a "control" layer to indicate the paths/rectangles that indicate slides and some transitions. While working on the file, I could hide that layer.
3. I used the Sozi plugin, I set up my presentation

This workflow had the following advantage: control and content where separated (by layers), but still linked by the absolute position in the .svg file. So, if I rearranged stuff in the SVG file (for instance, when I modified my presentation), I always had the content and the transitions linked.

Is this still possible in the standalone sozi15 editor?
The management of layers still confuses me deeply. I have the following issues/questions:
- Can I hard-link two layers, e.g. the one with the control to the one with the content, so that I do not by mistake zoom in one one and not on the other?
- How is it decided, what goes on the default layer? If I load my current file into Sozi15, and disable visibility of the default layer, some things vanish and some don't, though they are on the same layer in Inkscape.
- In general: How, when using Inkscape, would you separate content and control? Sure, I can do all on the same layer, take the control elements as reference in Sozi15 and choose to hide them. However, having these control elements always visible in the SVG editor (Inkscape) is deeply irritating.

**Comment by senshu** [comment]
> Can I hard-link two layers, [...]?

No. If I understand your need correctly, maybe you could create sub-layers in Inkscape. Each "content" layer could have its own "control" sub-layer.

> How is it decided, what goes on the default layer?

This is a manual process. In the timeline panel of the editor, you add all the layers that you want to manage separately. Other layers goes to the "default" group.

> If I load my current file into Sozi15, and disable visibility of the default layer, some things vanish and some don't, though they are on the same layer in Inkscape.

I suppose this is a bug. Can you send me an example document that illustrates the problem?

**Comment by beralt85** [comment]
> Each "content" layer could have its own "control" sub-layer.

I am not sure if I understand correctly, but I will give it a try.

> I suppose this is a bug. Can you send me an example document that illustrates the problem?

 I am travelling at the moment (actually touring on scientific conference with my sozi slides), so I am pretty busy. I will create minimal examples regarding the bugs I found as soon as I have some time left. Do you have an e-mail address where I can send files to?
In the meanwhile, one of my presentations can be found [here](http://presentations.beralt.com/2015-05-snowbird/). 

If you visit the page, make sure you use chrome. An [earlier presentation](http://presentations.beralt.com/2015-04-oldenburg/) worked fine in firefox (and had some issues in chrome), but now it seems to be the other way round. I have no idea where the problem lies, but I will provide proper bug reports/minimal examples when I am back home (in June).

**Comment by senshu** [comment]
@beralt85 OK. I will need the SVG and JSON files to reproduce the issues. Can you upload them to the same server as your other presentations?

**Comment by beralt85** [comment]
@senshu I've prepared a small [example](https://beralt.pictor.uberspace.de/owncloud/public.php?service=files&t=e925ce38c0f9cc5c162834ab420c74af) file demonstrating the two bugs I found:

 1. In Mozilla Firefox, some of the objects on the slides are not displayed. Yet it works in Google Chrome and the Ubuntu Web Browser.
 2. According to inkscape, the .svg file only contains one layer. In Sozi 15 (e.g. Sozi-15.04.281146-linux64), when deactivating the visibility of the "default" layer, some objects vanish and other stay visible.

Hope this is useful to you. Sorry for taking so long, I just came back from my travels a couple of days ago.

**Comment by senshu** [comment]
> In Mozilla Firefox, some of the objects on the slides are not displayed. Yet it works in Google Chrome and the Ubuntu Web Browser.

When I open the original SVG in Firefox, those objects are not displayed either. I have noticed problems with SVG in Firefox lately: examples that worked in earlier versions are no longer rendered correctly.

> when deactivating the visibility of the "default" layer, some objects vanish and other stay visible

This is a bug in the editor. I think it deserves it own bug report.

**Comment by beralt85** [comment]
> problems with SVG in Firefox lately: examples that worked in earlier versions are no longer rendered correctly.

I'll file a firefox bug report then.

> This is a bug in the editor. I think it deserves it own bug report.

You are right. This one has become a littler confusing - my bad. I will open a new bug report and describe the problem.

**Comment by aumouvantsillage** [comment]
I am closing this old issue. If you think it is still relevant today, please open a new issue.
