### ISSUE TITLE
Create links between presentations

### ISSUE THREAD

**Issue by charles-plessy** [sozi-projects/Sozi#421]
### Feature request

My presentations are getting quite large and I miss an easy way to blend a new presentation based on two or more old ones.

Would it be possible to add an option allowing one to navigate between Sozi files ?  This way, one presentation session would be prepared by first creating topic-focused Sozi presentations, and then linking them in the desired order. This would facilitate reuse a lot.

(I tried to reach the same result by embedding Sozi HTML files into _slidy_ presentations generated with _Pandoc_, with no success.)

**Comment by senshu** [comment]
At the moment, the recommended method is to use hyperlinks.
The [tutorial](http://sozi.baierouge.fr/pages/tutorial-links.html) is not up to date, but the feature exists in Sozi 18 as well.

I understand that it is not exactly what you want, so we can keep this feature request open.

**Comment by joancf** [comment]
Do you mean a kind of master/slaves presentation. You have a master presentation, that switches forth and back to/from the slaves presentations?.

**Comment by aumouvantsillage** [comment]
I am closing this old issue. If you think it is still relevant, please feel free to open a new one and clarify your request.
