### ISSUE TITLE
Can not open a file at the first attempt on OS X

### ISSUE THREAD

**Issue by charles-plessy** [sozi-projects/Sozi#463]
Hello,

on OS X 10.14.6, when I launch Sozi for the first time and attempt to load a SVG file, nothing happens.  However, if I quit Sozi and start it again it for a second attempt it works. It is a bit puzzling...

I experienced this with versions 19.04 and 18.04; I have not tested other versions.

Have a nice day and thanks again for your work on Sozi!

**Comment by senshu** [comment]
I have fixed an issue related to file opening in Sozi 19.09 (available from https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0?usp=sharing ).
However, it seems that your problem is different.

I will try to reproduce it, but I don't have a computer running OS X.

**Comment by gotjoshua** [comment]
I also experienced this with the newest Beta ( [v20.01-beta](https://github.com/senshu/Sozi/releases/tag/v20.01-beta) ), and after quitting Sozi fully and opening again, opening the svg worked fine.

**Comment by kurka** [comment]
Exprerienced the same issue, but on Arch Linux, installing the aur package (19.04-2).

**Comment by senshu** [comment]
@kurka Please try the new pre-release 20.03 and tell me if it works better for you.

**Comment by aumouvantsillage** [comment]
This issue has been inactive for almost two years. I have received no answer to my requests for feedback.
If you still have this problem, please open a new issue.

**Comment by charles-plessy** [comment]
Just tested Sozi 22.03 and did not experience the issue, thanks!
