### ISSUE TITLE
Can't move frames

### ISSUE THREAD

**Issue by Trekky12** [sozi-projects/Sozi#484]
### Summary of your problem or feature request

Unfortunately it is not possible to move the frames in the timeline. Addiontionally the move backwards button has the same icon like the move forward icon.

### Version of Sozi and other relevant software

* Which version of Sozi are you using?
  * I tested it with 20.05 and 19.04
* On which platform? (examples: Windows 7 64-bit, Ubuntu Linux 14.04 32-bit, OS X El Capitan 64-bit)
   * Windows 10 2004

### Steps to reproduce the problem

Open the first presentation file, create three frames and try to move the frames in the timeline backwards/forwards.

### Expected behavior

Frames are moved forward/backward

### Observed behavior

Nothing is happening

**Comment by Trekky12** [comment]
Apparently I didn't understand how to move frames correctly.
I though a frame could only moved one frame left/right.

The current behaviour, where you first select the slide to move and then select the destination is great 👍 

Maybe the moving of frames should be described somewhere.

**Comment by aumouvantsillage** [comment]
I agree that there is a lack of documentation for the user interface of Sozi.
I hope I can find time to complete it.
