### ISSUE TITLE
Feature request: Language picker in preferences menu

### ISSUE THREAD

**Issue by Gurbuzguven** [sozi-projects/Sozi#488]
Make sure that you have read the [documentation of Sozi](http://sozi.baierouge.fr),
and especially the [installation instructions](http://sozi.baierouge.fr/pages/20-install.html)
and the [frequently asked questions](http://sozi.baierouge.fr/pages/faq.html)
before reporting an issue.
Remember that this is not a place to ask questions.
If you want to get help on Sozi, you can join the [Sozi community forum](http://sozi.baierouge.fr/community/).

Describe your problem or propose a new feature in the following sections.
Keep the headings and replace the paragraphs with your own text.

### Summary of your problem or feature request

Adding language picker in preferences menu so that user can select other languages to use the program(Like in bilingual setup where operating system is english but user need the show someone the program in Turkish, German, Chinese etc.)(By the way i updated both Chinese Traditional and Simplified translations and also Turkish Translation)

### Version of Sozi and other relevant software

* Which version of Sozi are you using?
Sozi 20.08.16-1597572214 Linux 64 bit
* Which drawing software did you use? (examples: Inkscape 0.48, LibreOffice Draw 4.2)
Inkscape 1.0
* On which platform? (examples: Windows 7 64-bit, Ubuntu Linux 14.04 32-bit, OS X El Capitan 64-bit)
Google Chrome OS 84.0.4147.127 (64-bit) Linux(Beta) a.k.a Crostini 

### Steps to reproduce the problem

If you are proposing a new feature, what steps should the user follow to use it?

Manually select language from preferences menu so that user can use program in bilingual setup etc.

### Expected behavior

Manually select language from preferences menu

### Observed behavior

-

### Hints and solutions (optional)

[This](https://codyhouse.co/blog/post/accessible-language-picker) might help.

**Comment by aumouvantsillage** [comment]
Yes. I agree that it would be useful.
I could easily add a drop-down menu in the preferences of Sozi, but a restart would be needed to apply the change.

At the moment, Sozi uses the current sytem language (read from the `LANG` variable in Linux).
It can be changed from the command line by running Sozi like this:

```
LANG=tr sozi
```

**Comment by Gurbuzguven** [comment]
Thank you for quick reply and for this wonderful program.I will try to give you donation when i got money.You deserve it!!

**Comment by aumouvantsillage** [comment]
> I could easily add a drop-down menu in the preferences of Sozi, but a restart would be needed to apply the change.

Done. I will publish a new release with this feature soon.
It was fairly easy to implement. The tedious part being to map each language code to the appropriate native language name.
And we can change the language instantly without even restarting Sozi!

> Thank you for quick reply and for this wonderful program.I will try to give you donation when i got money.You deserve it!!

Thanks.
Contributing to Sozi with translations is already a great way to show your support :)

**Comment by Gurbuzguven** [comment]
Thanks.That's awesome.
