### ISSUE TITLE
Problem to install: TypeError: buildConfig.platforms.flatMap is not a function

### ISSUE THREAD

**Issue by EtienneAb3d** [sozi-projects/Sozi#493]
### Summary of your problem or feature request

When trying to install from sources, I get the following error at the `grunt` step:
```
~/SOZI-DEV/Sozi$ grunt
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: buildConfig.platforms.flatMap is not a function
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```
### Version of Sozi and other relevant software

Fresh git clone.

Tested systems (freshly updated): 
XUbuntu 20.04 LTS
XUbuntu 18.04 LTS

**Comment by aumouvantsillage** [comment]
Which version of node.js are you using?

**Comment by EtienneAb3d** [comment]
XUbuntu 20.04 LTS:
```
~/SOZI-DEV/Sozi$ apt-show-versions nodejs
nodejs:amd64/focal 10.19.0~dfsg-3ubuntu1 uptodate
```
XUbuntu 20.04 LTS:
```
~/SOZI-DEV/Sozi$ apt-show-versions nodejs
nodejs:amd64/bionic-updates 8.10.0~dfsg-2ubuntu0.4 uptodate
```

**Comment by EtienneAb3d** [comment]
Installing nodejs 14 with the procedure on that page solved the problem:
https://doc.ubuntu-fr.org/nodejs
```
wget -qO- https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt install -y nodejs
```
I had to build with `grunt --force` because of warnings stopping the process in some early steps.

**Comment by aumouvantsillage** [comment]
Yes. The build script requires node.js 11 or above.
