### ISSUE TITLE
Unwanted cropping effect after updating svg file

### ISSUE THREAD

**Issue by albertheres** [sozi-projects/Sozi#494]
First of all, Sozi works great!

# Problem
I notice some unwanted cropping effects after updating a multi layer svg file. The first time animating the svg file in Sozi works well, but after editing the svg file (in Inkscape) some cropping bars on top and bottom appears between the transition of the frames. I'm that the cropping option is unchecked for all frames. This problem only occurs with multiple layer svg files, not with single layer svg files.

## Screen capture of the problem
Here you can see the unwanted cropping effect in the screen captures: https://photos.app.goo.gl/t2zNNiFJSidvs1ti8 Notice that the color of the cropping bars are the background color of the svg file. In this case the unwanted cropping bars a quite small, but sometimes the are ±25% of the screen height.

# Cloud folder with source files
https://drive.google.com/drive/folders/13CtrwEPFiZ1MsbWsZ1b_cbokC7HjQ-NY?usp=sharing

# What I tried to solve it
- I tried multiple Windows computers
- I tried Linux computer
- Playing with transparant and black backgrounds (like apha channels)
- Alignment frames with a exact ratio (16:9) of the Sozi presentation

# Usefull information
- Sozi version 20.5
- Inkscape version 1.0.1

Hopefully there is a quick fix, or workaround to manage it.

**Comment by aumouvantsillage** [comment]
Thanks for reporting the issue.
I confirm that I get the same behavior with your files on my computer.

**Comment by aumouvantsillage** [comment]
Sorry for taking so long to fix this issue.

The problem was due to the fact that a clipping operation was always applied during transitions, even if neither the initial nor the final frame were clipped.

**Comment by aumouvantsillage** [comment]
I have just published [Sozi 21.12](https://github.com/sozi-projects/Sozi/releases/tag/v21.12). It contains a fix that addresses this issue.

**Comment by albertheres** [comment]
Thank you very much for this fix! Absolute no reason to say sorry. Well done!
