### ISSUE TITLE
keyboard shortcuts for "full page view" and "return to current page"

### ISSUE THREAD

**Issue by ckhung** [sozi-projects/Sozi#495]
### feature request: keyboard shortcuts for "full page view" and "return to current page" in browser presentation mode

Thanks for writing sozi! I have been using the inkscape-plugin version 13 up until very recently.
There are two keyboard shortcuts in browser presentation mode that I miss:
"f" for showing the entire page/canvas and "=" for returning to the current page.
Can we have them back in the stand-alone version please?

### Version of Sozi and other relevant software

I am running sozi 20.05.09-1589035558 on the xfce flavor of linux mint 20 ulyana.
Browser is firefox 79.0 .

### Expected behavior

For the "f" key, obviously I expect to see the entire canvas when I press it.

For the "=" key, for example I would press "r" to rotate the current slide
and then press "=" and expect this slide to return to its original orientation.

### Observed behavior

Nothing happens.

### Hints and solutions (optional)

On a related side note, what's the key for "turning the screen black"?
While browsing existing issues looking for similar feature requests I came across the closed issue 226
["Key shortcut to turn the screen black"](https://github.com/sozi-projects/Sozi/issues/226)
but didn't see which key I can press to create this effect.
It's not documented in [the "play" document"](https://sozi.baierouge.fr/pages/40-play.html)
and I failed to find it in the source code using a simple ```grep -ir black .```
Can you please point me to the portion of the code for handling
different cases of the keyboard input? Thanks!

**Comment by aumouvantsillage** [comment]
I don't remember why I removed the "f" and "-" keyboard shorcuts. I'll look into it.

> On a related side note, what's the key for "turning the screen black"?

The web site has been reorganized and the new address of the "play" document is https://sozi.baierouge.fr/pages/play.html
The "blank screen" feature can be activated by pressing the "." key.

**Comment by momeni** [comment]
Maybe, the `f` shortkey was removed because with several layers, the "**full page view**" would not remain well-defined. The expected zoom/rotation of each layer to correctly represent the "**full page view**" needs manual adjustment in the editor (maybe we can designate an specific frame as the "**full page view**" frame?).

By the way, I have prepared the pull request #537 in order to reintroduce the `=` short key (to cancel interactive zoom/rotations).

**Comment by aumouvantsillage** [comment]
I have pushed an implementation for these keyboard shortcuts:

* key "A" triggers the "view **a**ll" function (formerly "full page view")
* key "=" resets the view to the current frame. The implementation is based on the pull request by @momeni

**Comment by ckhung** [comment]
Thank you, guys! You are great!

**Comment by aumouvantsillage** [comment]
This feature is available in [release 21.08](https://github.com/sozi-projects/Sozi/releases/tag/v21.08)
