### ISSUE TITLE
Debian packages misses copyright file, package installers shows "Proprietary" license instead of "MPL-2.0"

### ISSUE THREAD

**Issue by valioDOTch** [sozi-projects/Sozi#496]
### Summary of feature request

The debian packages miss the debian/copyright file.
When trying to install the package the installer indicates a "proprietary" license, instead of "MPL-2.0"

### Version of Sozi and other relevant software

* Sozi v20.05
* Ubuntu 18.04.4 LTS 64-bit

### Steps to reproduce the problem

* Use a current Debian linux
* Download Sozi DEB package via https://github.com/sozi-projects/Sozi/releases/tag/v20.05
* Start to install the package

### Expected behavior

The package installer GUI shows "MPL-2.0" in the license field

### Observed behavior

The package installer GUI shows "Proprietary" in the license field
![image](https://user-images.githubusercontent.com/800467/95072666-d1c02f80-070b-11eb-8fba-406c4d7a15e1.png)

### Hints and solutions

* https://www.npmjs.com/package/grunt-license
* https://www.debian.org/doc/manuals/maint-guide/dreq.de.html#copyright
* https://dep-team.pages.debian.net/deps/dep5/

**Comment by aumouvantsillage** [comment]
I agree that this is an issue that needs to be fixed.

Thanks for pointing me to grunt-license.
Unfortunately, this package generates a 2800-line JSON file and needs further processing to get an acceptable Debian copyright file: the JSON file provides package names and versions, but not the paths to the corresponding files.

**Comment by aumouvantsillage** [comment]
The build system now uses [electron-installer-debian](https://github.com/electron-userland/electron-installer-debian/).
