### ISSUE TITLE
 option to generate a QR code frame

### ISSUE THREAD

**Issue by ckhung** [sozi-projects/Sozi#498]
### option to generate a QR code frame

Can we have an option for the user to add a URL for sozi to automatically generate a QR code frame?
In my speeches, I frequently boast sozi's cloud-friendliness as one advantage
over those non-cloud presentation file formats. (Can be opened w/ a competent browser, etc.)
Displaying QR code for its url will further emphasize this point.

### Version of Sozi and other relevant software

I am running sozi 20.05.09-1589035558 on the xfce flavor of linux mint 20 ulyana.
Browser is firefox 79.0 .

### Expected behavior

One adds a url in the editor and sozi then automatically generates a frame
for the user to insert into anywhere in the timeline.

### Hints and solutions (optional)

Might this code be useful for this feature?
https://davidshimjs.github.io/qrcodejs/

**Comment by Moini** [comment]
While I can't speak for the creator of Sozi, this seems very out of scope to me. Why don't you use Inkscape to create the QR codes?

**Comment by ckhung** [comment]
Yeah doing it manually in inkscape is an option. But doing it in sozi can facilitate further automation.
For example, if cleverly implemented, it may be possible to script this operation for mass processing.
I have two dozen old sozi presentations online that I used to batch-process (directly on the svg source file)
to change fonts and to change between relative/absolute linked images.
I imagine this feature when scripted can be helpful, for example, for batch uploading
many sozi presentations from various authors of a certain organization to a website.

**Comment by Moini** [comment]
There's an Inkscape extension that can be used for this: https://gitlab.com/Moini/nextgenerator

**Comment by aumouvantsillage** [comment]
Thanks for submitting this idea.

I agree that it could be useful but as @Moini pointed out, it seems that a general-purpose QR code generator, implemented as an Inkscape extension or maybe a web browser add-on, could be as effective.
Maybe I misunderstood your proposal, but I don't see a significant benefit in adding this feature to Sozi itself.

More generally, Sozi is designed with the following mindset: visual content creation is better handled by drawing applications such as Inkscape, and Sozi only deals with the "dynamic" aspects of your presentations.
As an example, the "add video or audio" feature for Sozi is implemented outside of the presentation editor, as an Inkscape extension.

**Comment by ckhung** [comment]
Thanks to @aumouvantsillage for the reply and thanks to @Moini for the link. OK I understand. I will check @Moini 's link for the approach from the inkscape side.

**Comment by Moini** [comment]
(Just to make it clear: the linked extension is for automatically embedding QR codes or any other changing content into multiple files. The QR codes themselves can be generated inside Inkscape, or by using the QR code extension on the command line.)
