### ISSUE TITLE
Sozi won't start on Debian Bullseye (Testing)

### ISSUE THREAD

**Issue by glerroo** [sozi-projects/Sozi#501]
### Summary of your problem or feature request

I have installed the last release from the deb file, and the program won't run.
Then i have opened a terminal and started Sozi from there. 
The result is the same but with this error log:
```
[6769:1205/033037.525006:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Sozi/chrome-sandbox is owned by root and has mode 4755.
[1]    6769 trace trap  sozi
```

### Version of Sozi and other relevant software

* Sozi version: 20.11.21
* Inkscape version: 1.01
* Libreoffice version: 7.0.3.1
* Debian GNU/Linux version: 11
* Distributor ID: Debian
* Description: Debian GNU/Linux bullseye/sid
* Release: testing
* Codename: bullseye
 
### Steps to reproduce the problem

* install with `sudo dpkg -i sozi_20.11.21-1605958474_amd64.deb`
* from a terminal launch `sozi`

### Hints and solutions (optional)

I have resolved with this command `sudo chmod 4755 /opt/Sozi/chrome-sandbox`

**Comment by aumouvantsillage** [comment]
Thanks for reporting.

There is a [conversation on this topic](https://sozi.baierouge.fr/community/d/123-sozi-20-on-debian-installation) in the user forum, but I had forgotten about it.
I will make sure the next released package has correct permissions.
