### ISSUE TITLE
First page is not being exported

### ISSUE THREAD

**Issue by nerusnayleinad** [sozi-projects/Sozi#507]
For some reason when I export my presentations to PDF, the first page is blank. I get it manually, then add to the PDF with another tool.

I was wondering if anyone knows how to solve the issue.

Usually, when I just export my presentations with the default values (sozi-to-export PRESENTATION), I get the PDFs quite out of focus, until I set the width and the height I used (-W 24 -H 12). But even then, the first page is blank.

I am using debian buster. I installed the tool without `-g` option, as I was getting the following error:

```
chmod failed: phantomjs was not successfully copied to /usr/local/lib/node_modules/sozi-export/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
```

**Comment by aumouvantsillage** [comment]
[https://github.com/sozi-projects/Sozi-export](Sozi-export) is considered obsolete and is no longer supported.
PDF export is now integrated in the presentation editor: I suggest you to try Sozi 21.02 and tell me if it solves your problem.

**Comment by 19ec94** [comment]
I installed the recent version of Sozi editor 21.02 following the instructions on https://github.com/sozi-projects/Sozi/releases/tag/v21.02 
I could not find any option to convert the presentation to PDF. Where do I find the option in the editor? 
I searched throughout the internet for a demo of sozi conversion to PDF. 
I was either directed to the archived sozi-to-pdf tool or to the sozi webpage which does not have any demo on this theme.

I installed Sozi version 21.02  on Ubuntu 18.04. 
It would be great if you could tell me what exactly the process for converting a sozi presentation html  to pdf. 
I look forward to try your suggestions. 
[P.S: It is really a nice tool. I look forward to using it. very well done! ]

**Comment by 19ec94** [comment]
Please ignore my previous comment. 
I have found the small export icon in the Sozi 21.02 Editor. :)  
It works beautifully.

**Comment by aumouvantsillage** [comment]
Thanks for your feedback.
I'm currently working on a better documentation for Sozi.
