### ISSUE TITLE
double-click glues view to mouse in viewless Sozi HTML page

### ISSUE THREAD

**Issue by NedNet29** [sozi-projects/Sozi#517]
### Summary of your problem or feature request

I'm using Sozi to create zoomable and draggable images, it's really great to embed big images in web pages (online training work).
So I simply open my SVG file with Sozi and do nothing else : the immediately generated HTML file already contains all what I need.
But when I open it with the browser, double-click on the image triggers a "glue-like" behavior : releasing the mouse click doesn't stop the image from dragging when mouse is moved.
I can only stop this by click-and-dragging the image again.

### Version of Sozi and other relevant software

* sozi 21.04.30
* I use Inkscape to generate my SVGs, but it happens also with a libreOffice Draw SVG export
* I use Sozi on windws 10, Inkscape and LibreOffice on Fedora 33
* bug appears with Firefox 88 (win & Fedora) MS Edge 90.0.818.56, Chromium  89.0.4389.90

### Steps to reproduce the problem

Open a SVG file with Sozi, close Sozi, open the HTML file generated by Sozi in a browser, double-click anywhere

### Expected behavior

I wish double-click would do nothing

### Observed behavior
(see summary )

### Hints and solutions (optional)

If I create just one view in Sozi, this doesn't happen anymore. But then each click resets the display to that view setting (size and position of the image), which is annoying for my users (trainees).
I don't expect them to double-click, but I guess double-click event is triggered when one clicks too quickly twice on the image.

**Comment by aumouvantsillage** [comment]
I have pushed a fix that automatically creates a dummy frame when playing a presentation.
As a result, clicks or double-clicks will no longer trigger the drag mode, but will move the canvas back to its initial position.

**Comment by NedNet29** [comment]
> clicks or double-clicks will no longer trigger the drag mode
Thank's for such reactivity. Can you confirm that it will be still possible to create simple drag&zoom images by creating a single frame presentation in which "support browser's back button" and "allow to control presentation" have been disabled, and other controls are enabled ?

**Comment by aumouvantsillage** [comment]
The fix is available in Sozi 21.05-beta.
As far as I can tell, it should not change the overall experience for you.

If you install it using the provided RPM package, please tell me how it goes.

>  just realized this week-end that doing so didn't make the glue behavior happen with Sozi 21.04.30

It makes sense. If you disable navigation with the mouse, the Sozi player will not attempt to move to a non-existent "next" frame on clicks.
