### ISSUE TITLE
deb mislabelled as proprietary

### ISSUE THREAD

**Issue by amunizp** [sozi-projects/Sozi#522]
### Summary of your problem or feature request

The deb package is assumed proprietary on ubuntu 20.04 deb installer. 

### Version of Sozi and other relevant software

* Which version of Sozi are you using? 21.02.21-1613918986

### Steps to reproduce the problem

What did you do to make the problem happen?
Go to https://sozi.baierouge.fr/pages/20-install.html
Download the deb 64 package. Double click on the downloaded package let it load on the ubuntu software centre. 
Under licence it labels it as Propietary in a green box. 

### Expected behavior

I would expect having the actual licence being labelled. GPL?

This is probably cosmetic and redundant if issue #496 #513 
![Screenshot from 2021-05-17 16-52-14](https://user-images.githubusercontent.com/5783911/118520222-cb7a4300-b731-11eb-90e1-843479cc77d4.png)

**Comment by aumouvantsillage** [comment]
> This is probably cosmetic and redundant if issue #496 #513

As far as I can tell, this is the exact same issue as #496
I have already commited a fix. The next release should show the correct license.
