### ISSUE TITLE
sozi extras add video 

### ISSUE THREAD

**Issue by Kunda27** [sozi-projects/Sozi#525]
Make sure that you have read the [documentation of Sozi](http://sozi.baierouge.fr),
and especially the [installation instructions](http://sozi.baierouge.fr/pages/20-install.html)
and the [frequently asked questions](http://sozi.baierouge.fr/pages/faq.html)
before reporting an issue.
Remember that this is not a place to ask questions.
If you want to get help on Sozi, you can join the [Sozi community forum](http://sozi.baierouge.fr/community/).

Describe your problem or propose a new feature in the following sections.
Keep the headings and replace the paragraphs with your own text.

### Summary of your problem or feature request

Write a short description of your problem.

### Version of Sozi and other relevant software

* Which version of Sozi are you using?
* Which drawing software did you use? (examples: Inkscape 0.48, LibreOffice Draw 4.2)
* On which platform? (examples: Windows 7 64-bit, Ubuntu Linux 14.04 32-bit, OS X El Capitan 64-bit)
* If your problem happens when playing a presentation, which browsers have you tried? (examples: Firefox 46, Chrome 52)

### Steps to reproduce the problem

What did you do to make the problem happen?
Give enough details to enable us to reproduce the problem.

If you are proposing a new feature, what steps should the user follow to use it?

### Expected behavior

What results did you expect?

### Observed behavior

What results did you actually get?

### Hints and solutions (optional)

* If you have taken the time to investigate the problem, tell us what you have found.
* If you have ideas on how to fix the problem, please describe them.

**Comment by Kunda27** [comment]
I'm desperately trying to live Prezi and move on sozi. the last problem is adding video. I'm tryng with your tutorial so I can see the purple car on firefox when I try to make the same creating svg document in Inkscape it does not work 
I work on  Sierra 10.12.6, using firefox and last version of Inkscape and sozi
In the browser it appears like the attached file but the ogv files does not start, the file is placed in the same folder of the sozi html file

![Schermata 2021-06-07 alle 11 55 41](https://user-images.githubusercontent.com/85487064/120997351-68575b80-c787-11eb-8633-b0fbf85fb943.png)

**Comment by aumouvantsillage** [comment]
Thanks for reporting your problem.
I will need more details to investigate the problem.

It would be great if you could report this issue again and fill the template with the requested information.
Sending me your files could help a lot.

**Comment by Kunda27** [comment]
What happens is that My Firefox last version on mac osx 10.12.6 does not
display the video, it shows the player but id does not visualize the
videofile.
Now maybe there is something missing in the inkscape svg preparation. In
facts looking at your tutorial parallax i see that the svg is already
opened in sozi with composed frames. This I don't understand while i know
that frames need to be created in sozi. Aniway as anthropologist and
educator I'm trying to build a system for teachers to compose and share
knowledge through sozi, that i find superbe, except for the inclusion of
audio and video.
I would like to strength a collaboration with you and include the usage of
sozi for european schools in an international project i'm writing for
university of Bologna. For this reason i need to be prepared on the usage
of the software......well on line there is plenty of tutorials but the
issue to include audio and video is still very difficult al least to me ,
having almost good digital skills. I don't like prezi business development,
and copyright issues, than i see sozi as a veri good alternative to build a
kind of teaching european enciclopedia with semantic issues so knowledge
patterns edited by sozi can be reachable inter operated and enriched.
Please help me to understand how let it work........hope you have a nice
weekend, My next project meeting with university office will be the 18th of
june , I hope to receive news from you before.
Thankyou very much excuse me, while I'm not straight in to programming and
coding , I'm socio anthropologist and educational trainer for teachers
but in my little mind I feel sozi is revolutionary, I really would like to
know more to use it better
best regards
Carlo Condarelli
I attached a small and simple experiment just including a video file in a
svg (the video file will be attached to next mail

Il giorno mer 9 giu 2021 alle ore 23:22 Guillaume Savaton <
***@***.***> ha scritto:

**Comment by NedNet29** [comment]
Hi, 
there is another way to play audios and videos inside a sozi presentation : see #516 
HTH
