### ISSUE TITLE
Problem loading an svg file (exported by LibreOffice impress)

### ISSUE THREAD

**Issue by MarimoMeer** [sozi-projects/Sozi#535]
Hello aumouvantsillage,

thanks for this nice software, I like it a lot :-)

### Summary of my problem
Sozi displays an empty page upon opening an svg file created by LibreOffice Impress.

### Version of Sozi and other relevant software
Sozi version: 21.02.21-16139
Drawing software used: LibreOffice Version: 6.1.5.2
Platform: Debian GNU/Linux 10 (buster)

### Steps to reproduce the problem
I am trying to make a sozi-slide show out of an odp/pptx file.
What I did was:
 1) create an odp file (test.odp) using LibreOffice Impress (test.odp is attached)
 2) export the test.odp file as an svg file.
 3) open the svg file with sozi

### Observed behavior
The outcome is that, sozi shows an empty page. (The same befaviour for pptx files converted to svg by LibreOffice)
I have pressed F12 in Sozi and checked the messages in the "Console" tab.
Here are the messages:

DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/appearances.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/operations.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/colors.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/operators.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/objects.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/errors.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/arrays.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/base64.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/strings.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/async.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/unicode.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/numbers.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/errors.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/objects.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/validators.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/pdfDocEncoding.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/Cache.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/syntax/CharCodes.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/PDFContext.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/document/PDFHeader.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFArray.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFNumber.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFObject.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFBool.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFDict.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFNull.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFName.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/syntax/Irregular.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/syntax/Delimiters.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/syntax/Whitespace.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFRawStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFRef.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/operators/PDFOperator.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/operators/PDFOperatorNames.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/structures/PDFContentStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/structures/PDFFlateStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/PDFObjectCopier.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/structures/PDFPageLeaf.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/writers/PDFWriter.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/document/PDFCrossRefSection.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/document/PDFTrailer.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/document/PDFTrailerDict.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/structures/PDFObjectStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/writers/PDFStreamWriter.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFInvalidObject.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/structures/PDFCrossRefStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/StandardFontEmbedder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFHexString.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/CustomFontEmbedder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/CMap.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/objects/PDFString.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/FontFlags.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/CustomFontSubsetEmbedder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/FileEmbedder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/JpegEmbedder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/PngEmbedder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/utils/png.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/PDFPageEmbedder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/streams/decode.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/streams/Ascii85Stream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/streams/DecodeStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/streams/Stream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/streams/AsciiHexStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/streams/FlateStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/streams/LZWStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/streams/RunLengthStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/structures/PDFCatalog.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroButton.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroTerminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroField.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/annotation/PDFWidgetAnnotation.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/annotation/BorderStyle.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/annotation/PDFAnnotation.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/annotation/AppearanceCharacteristics.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroCheckBox.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroChoice.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/flags.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroComboBox.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroForm.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroNonTerminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/utils.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroSignature.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroText.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroPushButton.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroRadioButton.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/acroform/PDFAcroListBox.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/interactive/ViewerPreferences.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/structures/PDFPageTree.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/parser/PDFObjectParser.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/parser/BaseParser.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/syntax/Numeric.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/parser/ByteStream.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/syntax/Keywords.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/parser/PDFObjectStreamParser.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/parser/PDFParser.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/parser/PDFXRefStreamParser.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/annotation/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/annotation/flags.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/rotations.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/svgPath.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/errors.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/text/layout.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/text/alignment.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/PDFButton.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/PDFPage.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/PDFDocument.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/PDFEmbeddedPage.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/PDFFont.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/PDFImage.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/PDFForm.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/PDFCheckBox.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/PDFField.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/image/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/image/alignment.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/PDFDropdown.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/PDFOptionList.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/PDFRadioGroup.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/PDFSignature.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/form/PDFTextField.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/StandardFonts.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/sizes.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/PDFDocumentOptions.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/PDFEmbeddedFile.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/PDFJavaScript.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/core/embedders/JavaScriptEmbedder.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/PDFPageOptions.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/api/text/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///opt/Sozi/resources/app/node_modules/pdf-lib/cjs/types/index.js.map: 

I would be very happy if you could help me.
[test.odp](https://github.com/sozi-projects/Sozi/files/6773182/test.odp)

**Comment by MarimoMeer** [comment]
...ok, I found a workaround.

If I first convert the odp/pptx file to pdf using LibreOffice,
then convert the pdf further to svg using inkscape, 
Sozi can open this svg file.
(But some letters went missing during the second conversion pdf --> svg.)

So I close this issue now.

**Comment by aumouvantsillage** [comment]
I'm glad you found a workaround.

I prefer to keep the issue open because I think it is worth investigating.
Unfortunately the error messages that you got are not related to your problem.

**Comment by MarimoMeer** [comment]
Thanks for your response.
I closed the issue because I didn't want to burden you and your team unnecessarily.
 
Can I still provide some more information for an investigation?
If yes, which information?
I really appreciate this Sozi project and your support :-)

**Comment by aumouvantsillage** [comment]
I have pushed a fix to the source repository. It will be available in a new release soon.

For the record, here is what I have found:
* In the generated SVG, the content of the slide is inside a group with the attribute `visibility="hidden"`. This is the reason why it was invisible in Sozi.
* However, when opening the SVG in a web browser (Firefox or Chromium), the slide is displayed correctly. When inspecting the document in the browser, we can see that the `visibility` has been changed to `"inherit"`.

This behavior is explained by the presence of a script inside the SVG that changes the visibility when the document is loaded in a browser. This script is disabled in Sozi.

It seems that this script is part of [JessyInk](https://code.google.com/archive/p/jessyink/), an SVG-based presentation tool that is no longer developed AFAIK. The reason for inserting this script is not clear since the SVG exported by Impress only contains one slide.

The fix that I have implemented in Sozi consists in removing several levels of nested groups, so that the slide content is an immediate child of the SVG root.

**Comment by MarimoMeer** [comment]
Thanks a lot for the fix!

**Comment by aumouvantsillage** [comment]
You're welcome.

As a side note, I do not recommend using Impress as a drawing tool, especially if your intent is to make a presentation with Sozi. While it should work in simple cases, the generated SVG is not compatible with some features of Sozi (layers, automatic alignment, transition paths).
