### ISSUE TITLE
Cannot load any SVG file created with LibreOffice Draw

### ISSUE THREAD

**Issue by aumouvantsillage** [sozi-projects/Sozi#547]
### Discussed in https://github.com/sozi-projects/Sozi/discussions/546

<div type='discussions-op-text'>

<sup>Originally posted by **troelsstru** August  5, 2021</sup>
Hi, I installed Sozi on my new laptop, but it cannot load any svg-file :-(

Can anyone help? I am NO EXPERT (just recently learned how to use the terminal), so I'm in need of simple explanations :-)

Thanks so much! Sozi is a great program! 

Here is more informaion:

I use
Ubuntu 20.04.2 LTS
Sozi release 21.08.02 

When I choose an svg-file, it doesn't give me any error message, it just doesn't load.
I have tried both by clicking "open an svg file" in the desktop version of sozi, and from a terminal: "sozi test.svg". The terminal code opens the program, but not the file.

When I press F12, here is the informaion:

__dirname=/usr/lib/sozi/resources/app/src/js	/usr/lib/sozi/resources/app/src/js/Storage.js:121 
Using handler: Impress	/usr/lib/sozi/resources/app/src/js/svg/SVGDocumentWrapper.js:182 
Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null

 at Function.transform (/usr/lib/sozi/resources/app/src/js/svg/ImpressHandler.js:32)
    at Function.fromString (/usr/lib/sozi/resources/app/src/js/svg/SVGDocumentWrapper.js:191)
    at Storage.loadSVGData (/usr/lib/sozi/resources/app/src/js/Storage.js:211)
    at Storage.setSVGFile (/usr/lib/sozi/resources/app/src/js/Storage.js:195)

After that, the message "DevTools failed to load SourceMap: Could not load content for file:///usr/lib/sozi/resources/app/node_modules/pdf-lib/cjs/index.js.map: ", repeated more than 100 times with different filenames. I'll be happy to post all these lines, if they are any help.

</div>

**Comment by edmundlaugasson** [comment]
Using 64-bit Linux Mint 20.2 Cinnamon (which is based on Ubuntu 20.04.2 LTS) and I could open SVG-file without any issues. Used *.deb file to install mentioned [Sozi release 21.08.02 ](https://github.com/sozi-projects/Sozi/releases/tag/v21.08.02). Also developer console at least opened with F12 without issues.

You can try to reinstall Sozi:
```
sudo apt-get clean
sudo apt purge sozi
sudo apt purge --auto-remove
sudo dpkg -i sozi_21.08.02-1627894333_amd64.deb
sudo apt install -f
sudo dpkg --configure -a
sudo ldconfig
```
Certainly either run these commands in folder, you downloaded Sozi or provide appropriate path to *.deb file.
Besides, when to click just on downloaded *.deb in Ubuntu graphical file manager, then it opens GDebi, which allows to install Sozi graphically and it will solve also dependencies automatically and asks confirmation to install them.

Also it might be useful to check, whether e.g. updates or any other installation has been completed and no issues:
```
sudo ldconfig
sudo apt install -f
sudo dpkg --configure -a
```

Sounds like [Ubuntu 20.04 LTS has still old version of Inkscape in repository](https://packages.ubuntu.com/search?keywords=inkscape&searchon=names&suite=all&section=all). You may want to install also [newest Inkscape 1.1](https://inkscape.org/release/1.1/gnulinux/) (currently) and create SVG-file(s) with that. There is also AppImage version available, which allows quickly check, whether the Inkscape version is the issue in your case. There is also official PPA available for newest Inkscape - [so you can also add that PPA and just update your system](https://inkscape.org/release/inkscape-1.1/gnulinux/ubuntu/ppa/dl/). Actually, [newest Inkscape is available via Flatpak also](https://www.flathub.org/apps/details/org.inkscape.Inkscape).

**Comment by aumouvantsillage** [comment]
@edmundlaugasson Thanks for your feedback.
In this specific case, the SVG was created with LibreOffice Draw, which is not supported at the moment.
You can find details in discussion #546
