### ISSUE TITLE
Estonian and other language translation activation not working in v21.08.02

### ISSUE THREAD

**Issue by edmundlaugasson** [sozi-projects/Sozi#556]
### Summary of your problem or feature request

Estonian translation activation not working in v21.08.02

### Version of Sozi and other relevant software

* Using:
  * [Sozi v21.08.02](https://github.com/sozi-projects/Sozi/releases/tag/v21.08.02), *.deb version
  * Drawing software Inkscape 1.1
  * On Linux Mint 20.2 Cinnamon, 64-bit

### Steps to reproduce the problem

Configured from settings to use Estonian language. Even after restarting Sozi, UI language was not changed. Tried also some other languages - same effect.

### Expected behavior

Would expect UI language being changed immediately. As far as I remember, even no app restart wasn't needed.

### Observed behavior

UI still in English after language change from Settings.

### Hints and solutions (optional)

Tried also some other languages, didn't also work.

**Comment by aumouvantsillage** [comment]
Thanks for reporting the issue.
I will publish a fixed release in a few days.
