### ISSUE TITLE
No scrolling of the list of views

### ISSUE THREAD

**Issue by epzt** [sozi-projects/Sozi#570]
When a presentation has lots of slides/views, I do not have a scroll bar at the bottom of Sozi, as it should normally appears when the number of slides/views goes out the screen viewport.

Version of Sozi : 21-09-14 1631646245
Drwing software : Inkscap 1.1
Xubuntu Linux 20.04 64-bit

Following a screenshot of the bottom of Sozi 
![Sozi-bottom](https://user-images.githubusercontent.com/4783343/139320123-ec1d7ca9-6d21-418e-9c7c-bf91f73591b2.png)

**Comment by aumouvantsillage** [comment]
The strange thing is that normally, scroll bars should always be visible even when they are not needed.
This is what I get when opening an SVG before adding frames or layers:

![Sozi-570](https://user-images.githubusercontent.com/120857/139695364-92e7aac1-2cc4-4032-83a3-52167f56ff39.png)

Have you added custom CSS styles to your SVG that could interfere with the user interface of Sozi?

**Comment by epzt** [comment]
Thanks for your answer.
I finally found yesterday what was wrong. Surprisingly on my system, when a windows openned in full screen, the bottom of my screen in the settings was a little bit outside the physical size of my laptop screen. In the present case, it was masking the scroll bar of Sozi in full screen. As my system task bar is on the bottom (and sets to diseaper when an application has the focus), I didn't noticed it immediatly. I apology for this mistake and thanks the community for its help.
I now going to promote Sozi around with my first presentation :)
