### ISSUE TITLE
Failed to write video file

### ISSUE THREAD

**Issue by albertheres** [sozi-projects/Sozi#574]
## Problem
I tried to export my Sozi presentation to a video. The error "Failed to write video file" appears after exporting. It doesn't matter if I choose for MP4, OGV or Webm. Only export as PNG frames works.

[screenshot](https://imgur.com/a/qofrexc
)
## What I tried to solve
1. Reinstalled Multimedia codecs and reinstalled Sozi 21.11
2. Removed Sozi 21.11 and replaced with Sozi 21.05

## System Info
OS: Linux Mint 20.2

**Comment by albertheres** [comment]
I don't understand why, but it works now. It might be due to some system updates. I have a brand new Linux Mint installation which can be busy with updating in the background.

**Comment by aumouvantsillage** [comment]
If it happens again, you may find additional error messages in the JavaScript console. (See [the last section of the README file](https://github.com/sozi-projects/Sozi#helping-debug-sozi))
Failed video export could be related to a problem with running ffmpeg.
