### ISSUE TITLE
Video could not be played in a project but could in another

### ISSUE THREAD

**Issue by lopippo** [sozi-projects/Sozi#582]
Greetings,

I have found a weird issue: I would like to play a video (mp4 or ogv) in a presentation. I included it using the Inkscape Sozi extension. When I play the saved presentation, I have a bad smiley message "No video with supported format...".

- I thought my video file was the issue. I downloaded the Sozi video tutorial and could play the presentation fine. I saved it again to make sure the v21.12.06 was not the issue. Fine.

- If I take my video and that I insert it into the tutorial project, the presentation works fine.

- If I take the tutorial video ogv file and I try to set it into my project, the presentation fails (same "No video with ..." message).

What could be the issue here ?

Yours, most sincerely,
Filippo

**Comment by Moini** [comment]
Does the video play in your browser? If not, try a different one.

**Comment by aumouvantsillage** [comment]
> What could be the issue here ?

Since your video works in the tutorial project, it seems that the problem is in your SVG document.
Since I cannot inspect it, I can suggest two possible causes:

* When inserting the video using the extension, maybe you set the wrong MIME type.
* Maybe the path of the video file is not correct.
