### ISSUE TITLE
Exponent notation shows in Inkscape, Sozi, PDF, but not presentation

### ISSUE THREAD

**Issue by lopippo** [sozi-projects/Sozi#583]
Greetings,

I am currently using Sozi to create a presentation where I need the exponential notation (i.e. 10 ^-12). Most interestingly, I find that the notation renders fine in Inkscape, inside the Sozi interface, and the PDF (export Sozi presentation to PDF) but not in HTML.

Please, see the test files in the attached archive.

Yours, most sincerely,
Filippo
[test.zip](https://github.com/sozi-projects/Sozi/files/7675782/test.zip)

**Comment by Moini** [comment]
Try a different browser or use another way to generate the formula (e.g. object-to-path in Inkscape), this doesn't appear to be anything that's fixable in sozi.

**Comment by lopippo** [comment]
> Try a different browser or use another way to generate the formula (e.g. object-to-path in Inkscape), this doesn't appear to be anything that's fixable in sozi.

Yes, indeed, in Chrome the page renders fine. Still an interesting problem, though. Closing.
