### ISSUE TITLE
Required dependencies for general Linux binary

### ISSUE THREAD

**Issue by medmedin2014** [sozi-projects/Sozi#591]
Can anyone please point to which package/library is really needed by the general linux binary ?

![Screenshot_20220104_151808](https://user-images.githubusercontent.com/7027319/148072849-617db6b4-76e2-47c1-a462-1761e9072780.png)

**Comment by aumouvantsillage** [comment]
The mandatory dependencies are those of [electron](https://www.electronjs.org/). For instance, the Debian package for Sozi uses the [list of dependencies from the electron-installer-debian tool](https://github.com/electron-userland/electron-installer-debian/blob/main/src/dependencies.js):

  atspi: 'libatspi2.0-0',
  drm: 'libdrm2',
  gbm: 'libgbm1',
  gconf: 'libgconf-2-4 | libgconf2-4',
  glib2: 'libglib2.0-bin',
  gtk2: 'libgtk2.0-0',
  gtk3: 'libgtk-3-0',
  gvfs: 'gvfs-bin',
  kdeCliTools: 'kde-cli-tools',
  kdeRuntime: 'kde-runtime',
  notify: 'libnotify4',
  nss: 'libnss3',
  trashCli: 'trash-cli',
  uuid: 'libuuid1',
  xcbDri3: 'libxcb-dri3-0',
  xdgUtils: 'xdg-utils',
  xss: 'libxss1',
  xtst: 'libxtst6'

The integrated video export feature of Sozi depends on FFMPEG, but it is not required to build the Sozi binary.

These other programs are related to Sozi but are completely optional:

* Inkscape
* sozi-extras-media
* sozi-extras_texts2paths

**Comment by aumouvantsillage** [comment]
I am closing this issue because it is neither a bug report nor a feature request.
Please consider the [discussion forum](https://github.com/sozi-projects/Sozi/discussions) if you want to ask further questions on this topic.
