### ISSUE TITLE
Unable to open many  (most) SVG files works in older versions

### ISSUE THREAD

**Issue by ironiemix** [sozi-projects/Sozi#599]
### Unable to open most SVG files

When I try to open SVG files, most of the time just nothing happens - after selecting the file sozi just displays a message that I should upload a svg file. This happens with sozi 22.02.01 installed in ubuntu 20.04 from the deb-Package.

When I downgrade sozi to version 21.12.06 the same file opens without problems. Some files open with 22.02.01 too, but even newly created files (with inkscape 0.92) will not open.

### Version of Sozi and other relevant software

* The problem is in version 22.02.01, it works in 21.12.06
* The problem occurs with various svg files, When I Create a new file with inkscape 0.92 it does not open.
* Zorin Linux, based on Ubuntu Linux 20.04 64-bit

### Steps to reproduce the problem

I tried to open the following SVG file: []()https://wiki.qg-moessingen.de/_media/rk.svg with sozi 22.02.01. The same file opens with sozi 21.12.06

**Comment by aumouvantsillage** [comment]
Sorry for the inconvenience.
I have uploaded a fixed version (Sozi 22.02.03). Please tell me if it works better for you.

**Comment by ironiemix** [comment]
Works fine again, thanks a lot for the quick response & fix!
