### ISSUE TITLE
Please publish your .spec file

### ISSUE THREAD

**Issue by logological** [sozi-projects/Sozi#636]
The source code for Sozi provided in this GitHub repository lacks the `.spec` file needed to generate the RPM published on the [Releases](https://github.com/sozi-projects/Sozi/releases) page.  Please consider adding this file to the repository, or else publishing it somewhere else and conspicuously documenting its location on the Releases page and/or in the Sozi documentation.  This will help others to package Sozi for RPM-based systems, and to help solve problems such as Issue #635.

**Comment by aumouvantsillage** [comment]
Answered in: https://github.com/sozi-projects/Sozi/issues/635#issuecomment-1170151656
